version: "3.8"

services:
  checkout:
    image: checkout
    build: ./checkout/
    ports:
      - 50051:50051
    depends_on:
      - postgres-checkout
    links:
      - postgres-checkout
    networks:
      - net
  loms:
    image: loms
    build: ./loms/
    ports:
      - 50052:50052
    depends_on:
      - postgres-loms
    links:
      - postgres-loms
    networks:
      - net
  notification:
    image: notification
    build: ./notifications/
    networks:
      - net

  # Postgres
  postgres-loms:
    image: postgres:15.1
    environment:
      POSTGRES_DB: loms
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    container_name: 'postgres-loms'
    volumes:
      - ./db/loms:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d loms" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - net
  postgres-checkout:
    image: postgres:15.1
    environment:
      POSTGRES_DB: checkout
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    container_name: 'postgres-checkout'
    volumes:
      - ./db/checkout:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d checkout" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - net

  # kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
    networks:
      - net
  kafka1:
    image: confluentinc/cp-kafka:latest
    ports:
      - 29091:29091
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29091
    container_name: 'kafka1'
    depends_on:
      - zookeeper
    networks:
      - net
  kafka2:
    image: confluentinc/cp-kafka:latest
    ports:
      - 29092:29091
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29091
    container_name: 'kafka2'
    depends_on:
      - zookeeper
    networks:
      - net
  kafka3:
    image: confluentinc/cp-kafka:latest
    ports:
      - 29093:29091
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:29091
    container_name: 'kafka3'
    depends_on:
      - zookeeper
    networks:
      - net
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8946:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: homework
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:29091,kafka2:29091,kafka3:29091
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - net
networks:
  net:
