app:
  name: loms
  port: 50052
  env: dev

database:
  host: postgres-loms
  port: 5432
  user: user
  password: password
  name: loms

brokers:
  - kafka1:29091
  - kafka2:29092
  - kafka3:29093

logger:
  level: info
