app:
  port: 50051

product_service:
  url: route256.pavl.uk:8082
  token: testToken

loms:
  url: loms:50052

database:
  host: postgres-checkout
  port: 5433
  user: user
  password: password
  name: checkout
